---
abstract: 'Encode latitude and longitude in a useful string format'
author:
  - 'Kyle Dawkins, <info[at]kyledawkins.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-DNA
no_index:
  directory:
    - inc
    - t
requires:
  Math::Trig: 0
  POSIX: 0
  common::sense: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
